### ISSUE TITLE
hey how/what can i contribute

### ISSUE THREAD

**Issue by shrey141102** [GDSC-Aliah/Portfolio-Maker#1]

**Comment by AvirukBasak** [comment]
Start by forking this repo.

You can contribute by improving the repo in a way that improves it.

All improvements to the repo are welcome.

You can also contribute by creating your portfolio using the template provided at the `Template` directory.

You can then put the profile you just made using the template to the `Portfolio` folder, and then open a PR.

**Comment by shrey141102** [comment]
sure
